### PR TITLE
Archive 1.10.0 migrations

### PR DESCRIPTION
**Pull request by arnaldo2792**
**Description of changes:**
Regardless of the next release version, archiving migrations improves builds' speed. This is similar to what was done in #2357 and #1699.

**Testing done:**
Builds are successful after archiving the migrations.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by webern** [comment]
I can think of reasons we might want to keep the last N versions around. Was there a discussion and decision that we will archive migrations right away after a release?

**Comment by arnaldo2792** [comment]
> Was there a discussion and decision that we will archive migrations right away after a release?

Yes, but wasn't registered anywhere :crying_cat_face: and it happened too long ago so I don't remember most of the discussion. But we can start a thread now:

I do remember that the argument was that we end up spending time (multiplied by all the variants) building artifacts that already exist in the tuf repos. This also affects the github workflows execution time.

**Comment by stmcginnis** [comment]
I remember the discussion, but I don't remember where. The key realization for me was that archiving the migrations doesn't mean someone can't upgrade from one of those older versions. The migrations are still available, they just aren't rebuilt every time.

**Review by stmcginnis — APPROVED** [review]
lgtm

**Comment by etungsten** [comment]
> I can think of reasons we might want to keep the last N versions around

Can you elaborate on some of them?

**Comment by webern** [comment]
> > I can think of reasons we might want to keep the last N versions around
> 
> Can you elaborate on some of them?

I was mostly thinking about development work in which you want to build a repo with a few earlier versions to check migration paths, but I guess you would build from tags for that anyway, so nevermind.

**Review by etungsten — DISMISSED** [review]

**Review by webern — CHANGES_REQUESTED** [review]
Well, I hadn't considered this eventuality, but it looks like we want to fix a bug in a 1.10.x migration: #2523 

I'm marking this as "Request Changes" to pause merging for now.

**Comment by arnaldo2792** [comment]
@stmcginnis created #2523 to fix the migration, I'll remove that migration this PR.

**Comment by arnaldo2792** [comment]
(forced push adds back the 1.10.1 migrations, but I forgot to removed them from archive and add them to `sources/Cargo.toml`)

**Comment by arnaldo2792** [comment]
(forced push adds back v1.10.1 migrations to `sources/api/migration/migrations` and to `sources/Cargo.toml` / `sources/Cargo.lock`)

**Comment by arnaldo2792** [comment]
(forced push is a rebase onto develop, to make sure I have the fixes in https://github.com/bottlerocket-os/bottlerocket/pull/2523)

**Review by webern — APPROVED** [review]

**Review by etungsten — APPROVED** [review]

**Pull request merged**
