### PR TITLE
Remove aws-k8s-1.18 variant

### LINKED ISSUE #1942: Deprecate aws-k8s-1.18 variant by March 2022
Kubernetes 1.18 went out of upstream support in June, 2021. AWS EKS is maintaining support for 1.18 until [March 31st, 2022](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). Bottlerocket will deprecate support of our `aws-k8s-1.18` variant by then.

While you’ll still be able to launch `aws-k8s-1.18` nodes beyond March 31st, 2022, we’ll no longer provide updated `aws-k8s-1.18` images, and the Bottlerocket repositories will no longer receive new updates for nodes running `aws-k8s-1.18`.

We recommend you replace existing Bottlerocket `aws-k8s-1.18` nodes with [a newer variant](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#variants) such as `aws-k8s-1.21` - ideally the latest your Kubernetes cluster supports.

For instructions on how to migrate your nodes to newer supported versions, please consult the [EKS documentation for updating clusters](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) or reach out to us through your AWS support channels for additional questions.

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
Fixes https://github.com/bottlerocket-os/bottlerocket/issues/1942

**Description of changes:**
```
    Remove aws-k8s-1.18 variant
    
    EKS ended 1.18 support on March 31st 2022.
```
```
    README: update example commands for fetching kmod kit
    
    The old example no longer worked due to tuftool download changes

```
Like https://github.com/bottlerocket-os/bottlerocket/pull/1807 removing 1.17, this removes the `aws-k8s-1.18` variant. It's no longer supported by k8s upstream or EKS. Deprecation was communicated in the issue linked above and in the 1.6.0 release notes / changelog.

**Testing done:**
Confirmed that unit tests pass, 1.18 is no longer referenced and doesn't build, and 1.19 is still healthy.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by webern — APPROVED** [review]

**Review by zmrow — APPROVED** [review]
:meat_on_bone:

**Review by bcressey — APPROVED** [review]

**Review by arnaldo2792 — APPROVED** [review]
Shouldn't the version in the commit message be `1.18` instead of `1.17`? Otherwise, approved.

**Comment by etungsten** [comment]
Push above fixes commit message

**Review by cbgbt — APPROVED** [review]

**Review by zmrow — APPROVED** [review]
:light_rail:

**Pull request merged**
