### PR TITLE
tough async

### LINKED ISSUE #3559: use tough async in migrator and updog
## Description

When `tough` switches to the Rust async interface, we will need to test the changes in updog and migrator, etc. Once testing is completed and a release of tough is done, we will need to update tough in Bottlerocket

## Definition of Done

- [ ] We have tested the un-released tough async interface
- [ ] We have updated tough to a released version using the async interface

### PR DESCRIPTION
**Pull request by webern**
**Issue number:**

- Closes #3559 
- Related https://github.com/awslabs/tough/pull/687
- Related https://github.com/bottlerocket-os/twoliter/pull/98

**Description of changes:**

Use `tough` in its `async` incarnation.

**Testing done:**

- [x] Before the PR landed 
  - [x] Run an image
  - [x] Downgrade with migrations
  - [x] Upgrade with migrations
 - [x] Repeat the above once we have a released version of `tough` with these changes. 

Note: during the re-test, when I looked at migrator's jounral entries I saw some errors on downgrade. This is was v1.15.1 which was built from the tag (and thus not running the new async code).

```
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.1_updog-network-affected.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_schnauzer-v2-generators.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_public-control-container-v0-7-5.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_aws-control-container-v0-7-5.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [ERROR] Migration stderr: 'settings.host-containers.control.source' has no 'template' key in metadata
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_public-admin-container-v0-11-1.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_aws-admin-container-v0-11-1.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [ERROR] Migration stderr: 'settings.host-containers.admin.source' has no 'template' key in metadata
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-settings.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-restart.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-files.lz4'
Nov 29 19:33:13 localhost migrator[941]: 19:33:13 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-configs.lz4'
```

On upgrade (running the new async code) I did not see these errors. For the purposes of these PRs, the testing shows that migrator is working correctly. Someone may want to look into the host container migrations on downgrade to see what's up.

```
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-configs.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-files.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-restart.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_kernel-modules-autoload-settings.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_aws-admin-container-v0-11-1.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_public-admin-container-v0-11-1.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_aws-control-container-v0-7-5.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_public-control-container-v0-7-5.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.0_schnauzer-v2-generators.lz4'
Nov 29 22:58:47 localhost migrator[942]: 22:58:47 [INFO] Running migration 'migrate_v1.16.1_updog-network-affected.lz4'
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/bottlerocket/compare/c4e1ebd0b32c7fbf4e097451ae1eaf60bd45d7f7..7ae81a9cb8e1e4c531288d4b99b279cc1cd1e18a

Update PR to released version of tough async.

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/bottlerocket/compare/8f4dd999204c568b55ce43ae5c0912a0d27620de..4bd61e9de85fece5a81146b6542d8eb1055bdb96

Rebase

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/bottlerocket/compare/4bd61e9de85fece5a81146b6542d8eb1055bdb96..3fae5483acefa97c3fa89e5b510853966f63324c

Fix an issue in updog.

**Review by etungsten — APPROVED** [review]

**Comment by etungsten** [comment]
Would be good to triage the errors on downgrade for the host-containers migration.

**Review by zmrow — APPROVED** [review]

**Comment by webern** [comment]
> Would be good to triage the errors on downgrade for the host-containers migration.

I have confirmed that this happens when running a `v1.16.1` Bottlerocket built from develop (`b375585`) and downgrading to an image built at the `v1.15.1` tag. I created an issue to track this unrelated problem: https://github.com/bottlerocket-os/bottlerocket/issues/3629

**Pull request merged**
