### PR TITLE
fix clippy lints for netdog

### PR DESCRIPTION
**Pull request by bcressey**
**Issue number:**
N/A

**Description of changes:**
Fixes all current lints for `netdog`.

**Testing done:**
```
❯ cargo clippy
   Compiling imdsclient v0.1.0 (/home/fedora/brdev/sources/imdsclient)
    Checking netdog v0.1.0 (/home/fedora/brdev/sources/api/netdog)
    Finished dev [unoptimized + debuginfo] target(s) in 4.08s

❯ cargo clippy --tests
    Checking netdog v0.1.0 (/home/fedora/brdev/sources/api/netdog)
    Finished dev [unoptimized + debuginfo] target(s) in 3.92s
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by bcressey** [comment]
Unfortunately, we don't run `cargo clippy --tests` in CI, and we also don't run `cargo clippy` for non-default features like the systemd-networkd support. That's why these made it through the earlier PRs.

**Review by stmcginnis — APPROVED** [review]
Great cleanup!

**Review by zmrow — APPROVED** [review]
Thanks!

**Review by yeazelm — APPROVED** [review]
This removes some of the code we no longer need since we decided to go with resolved but we also don't need `sources/api/netdog/src/cli/primary_interface.rs` and the code it brings in either so we should probably clean that up as well.

**Review by yeazelm — APPROVED** [review]
Nice!

**Review by zmrow — APPROVED** [review]
Thanks!

**Pull request merged**
