### PR TITLE
fix OpenApi spec link in readme

### PR DESCRIPTION
**Pull request by mgsharm**
**Issue number:** N/A

Closes # N/A

**Description of changes:**
- Fixes broken link for `OpenApi` spec in ReadMe.md 

**Testing done:**

Open the hyperlink in ReadME and checked it worked and pointed to correct file.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by sumukhballal** [comment]
There are a few links that are missing that could be part of this PR too. Like most of the packages/* links, most of which have moved. We'd probably want to add all of them into one documentation update PR, so its a bit easier on the reviewers and keeps our commit history a bit cleaner.

Examples:
```
https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/ecs-agent
...
https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/api/early-boot-config
...
etc
```

**Comment by mgsharm** [comment]
> There are a few links that are missing that could be part of this PR too. Like most of the packages/* links, most of which have moved. We'd probably want to add all of them into one documentation update PR, so its a bit easier on the reviewers and keeps our commit history a bit cleaner.
> 
> Examples:
> 
> ```
> https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/ecs-agent
> ...
> https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/api/early-boot-config
> ...
> etc
> ```

**Review by webern — APPROVED** [review]

**Comment by mgsharm** [comment]
Fixed more links that were broken.

**Review by jmt-lab — APPROVED** [review]
LGTM

**Comment by sumukhballal** [comment]
Nice, thanks!

**Review by sumukhballal — APPROVED** [review]

**Pull request merged**
