### PR TITLE
Update SDK to 0.36.1

### PR DESCRIPTION
**Pull request by jpculp**
**Description of changes:**

Update SDK to **v0.36.1**. Includes fixes from https://github.com/bottlerocket-os/bottlerocket-sdk/compare/v0.36.0...cb63e822d7aa05ba2e54cad99678986445dada45

_(Mainly swapping Go **1.21** for **1.20**.)_

**Testing done:**

https://github.com/bottlerocket-os/bottlerocket-sdk/pull/151

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by etungsten — APPROVED** [review]

**Review by yeazelm — APPROVED** [review]

**Review by etungsten — APPROVED** [review]

**Review by yeazelm — APPROVED** [review]

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to central-stage: [v202401.73.0](https://github.com/auth0/layer0-base/releases/tag/v202401.73.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel central-stage

# To see what was released to central-stage:
LAYER0_PROFILE=prod layer0 releases get v202401.73.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to central-stage: [v202401.73.0](https://github.com/auth0/layer0-base/releases/tag/v202401.73.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel central-stage

# To see what was released to central-stage:
LAYER0_PROFILE=prod layer0 releases get v202401.73.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-stage: [v202401.71.0](https://github.com/auth0/layer0-base/releases/tag/v202401.71.0) [dev]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=dev layer0 rc deploy list --release-channel pops-stage

# To see what was released to pops-stage:
LAYER0_PROFILE=dev layer0 releases get v202401.71.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-canary: [v202401.71.0](https://github.com/auth0/layer0-base/releases/tag/v202401.71.0) [dev]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=dev layer0 rc deploy list --release-channel pops-canary

# To see what was released to pops-canary:
LAYER0_PROFILE=dev layer0 releases get v202401.71.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-stage: [v202401.86.0](https://github.com/auth0/layer0-base/releases/tag/v202401.86.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel pops-stage

# To see what was released to pops-stage:
LAYER0_PROFILE=prod layer0 releases get v202401.86.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-stage: [v202401.71.0](https://github.com/auth0/layer0-base/releases/tag/v202401.71.0) [dev]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=dev layer0 rc deploy list --release-channel pops-stage

# To see what was released to pops-stage:
LAYER0_PROFILE=dev layer0 releases get v202401.71.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-canary: [v202401.86.0](https://github.com/auth0/layer0-base/releases/tag/v202401.86.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel pops-canary

# To see what was released to pops-canary:
LAYER0_PROFILE=prod layer0 releases get v202401.86.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-canary: [v202401.71.0](https://github.com/auth0/layer0-base/releases/tag/v202401.71.0) [dev]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=dev layer0 rc deploy list --release-channel pops-canary

# To see what was released to pops-canary:
LAYER0_PROFILE=dev layer0 releases get v202401.71.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-stage: [v202401.86.0](https://github.com/auth0/layer0-base/releases/tag/v202401.86.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel pops-stage

# To see what was released to pops-stage:
LAYER0_PROFILE=prod layer0 releases get v202401.86.0
```

**Comment by auth0build** [comment]
#### :white_check_mark: layer0: Deployed to pops-canary: [v202401.86.0](https://github.com/auth0/layer0-base/releases/tag/v202401.86.0) [prod]

This pull request was originally included in [v202401.69.0](https://github.com/auth0/layer0-base/releases/tag/v202401.69.0)

```bash
# To check the status of this release channel:
LAYER0_PROFILE=prod layer0 rc deploy list --release-channel pops-canary

# To see what was released to pops-canary:
LAYER0_PROFILE=prod layer0 releases get v202401.86.0
```

**Pull request merged**
