### PR TITLE
update to SDK v0.31.0

### PR DESCRIPTION
**Pull request by jpculp**
**Description of changes:**

Update SDK to v0.31.0.

**Testing done:**

See https://github.com/bottlerocket-os/bottlerocket-sdk/pull/103.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by jpculp** [comment]
Addressed `clippy` error rename.

**Review by jpmcb — APPROVED** [review]

**Comment by jpculp** [comment]
Removed temporary commit. Ready for review.

**Review by stmcginnis — APPROVED** [review]
lgtm

**Review by jpmcb — APPROVED** [review]
🥏

**Pull request merged**
