### PR TITLE
kernel-5.10: enable support for broadcom ethernet cards

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
N/A

**Description of changes:**
```
    kernel-5.10: enable support for broadcom ethernet cards
    
    This enables support for Broadcom Tigon3 based gigabit Ethernet cards.
```

I left out the config changes from kernel-5.4 since metal variants only use 5.10 kernel and 5.4 kernel doesn't have intel network support which is in kernel-5.10's config.

**Testing done:**
Built metal-k8s-1.21 image and provisioned it to a Dell PowerEdge R240 which uses a Broadcom network card for ethernet. Bottlerocket was able to boot fine and wicked was able get a DHCP4 lease without problem:

```
bash-5.1# dmesg | grep tg3                 
[    7.725969] tg3 0000:04:00.0 eth0: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address cc:48:3a:11:f0:39
[    7.755566] tg3 0000:04:00.0 eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    7.793438] tg3 0000:04:00.0 eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[    7.826115] tg3 0000:04:00.0 eth0: dma_rwctrl[00000001] dma_mask[64-bit]
[    7.909140] tg3 0000:04:00.1 eth1: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address cc:48:3a:11:f0:3a
[    7.934674] tg3 0000:04:00.1 eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    7.934675] tg3 0000:04:00.1 eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[    7.934676] tg3 0000:04:00.1 eth1: dma_rwctrl[00000001] dma_mask[64-bit]
[   13.217927] tg3 0000:04:00.0 eth0: Link is up at 1000 Mbps, full duplex
[   13.233301] tg3 0000:04:00.0 eth0: Flow control is on for TX and on for RX
[   13.249315] tg3 0000:04:00.0 eth0: EEE is enabled
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by bcressey** [comment]
Can you post the final kernel config diff for both architectures?

**Review by zmrow — APPROVED** [review]
:national_park:

**Comment by etungsten** [comment]
x86_64 without this change vs x86_64 with this change:
```
diff --git a/x86_kconfig_without b/x86_kconfig_with
index 6771b01..dc26feb 100644
--- a/x86_kconfig_without
+++ b/x86_kconfig_with
@@ -2356,7 +2356,16 @@
  # CONFIG_NET_VENDOR_ARC is not set
  # CONFIG_NET_VENDOR_ATHEROS is not set
  # CONFIG_NET_VENDOR_AURORA is not set
- # CONFIG_NET_VENDOR_BROADCOM is not set
+ CONFIG_NET_VENDOR_BROADCOM=y
+ # CONFIG_B44 is not set
+ # CONFIG_BCMGENET is not set
+ # CONFIG_BNX2 is not set
+ # CONFIG_CNIC is not set
+ CONFIG_TIGON3=m
+ CONFIG_TIGON3_HWMON=y
+ # CONFIG_BNX2X is not set
+ # CONFIG_SYSTEMPORT is not set
+ # CONFIG_BNXT is not set
  # CONFIG_NET_VENDOR_BROCADE is not set
  CONFIG_NET_VENDOR_CADENCE=y
  # CONFIG_MACB is not set

```

There's something crazy going on with aarch64 kernel build. Apparently without this change, `CONFIG_NET_VENDOR_BROADCOM` is set by default in the kernel config. 

```
 CONFIG_NET_VENDOR_BROADCOM=y
 # CONFIG_B44 is not set
 # CONFIG_BCMGENET is not set
 CONFIG_BNX2=m
 # CONFIG_CNIC is not set
 CONFIG_TIGON3=m
 CONFIG_TIGON3_HWMON=y
```

I tried aarch64 builds without this change on different machines and this is always set. I have no idea why it's set.

The aarch64 kernel config is same with or without this change.

**Comment by etungsten** [comment]
Apparently the AL2 kernel config differs on this between x86_64 and aarch64.

aarch64 kernel config has Broadcom TG3 support enabled by default, whereas x86_64 does not.

**Comment by foersleo** [comment]
The difference in AL2 config between the two architectures is indeed interesting. For such things as driver support for network devices I would not expect any differences there. Definitely something we should discuss with the team.

**Review by foersleo — APPROVED** [review]

**Review by bcressey — APPROVED** [review]

**Review by markusboehme — APPROVED** [review]

**Pull request merged**
