### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PrashantMehta-coder**
**Issue number:**

**Description of changes:**

**Testing done:**

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by tjkirch** [comment]
Hi @PrashantMehta-coder, thanks for your interest!  Would you please explain your thoughts around this change?  I think the original is a more common wording, but I'm interested to hear what you think.

**Comment by PrashantMehta-coder** [comment]
Thanks for the response, common words are used by everyone.. But, we should use some complex words which will increase our knowledge of words and grammar level.

**Comment by tjkirch** [comment]
In Bottlerocket docs, we aim for comfortable, common language that's easier to understand, so the reader can focus on the important parts.  So, in this case we're going to stick with the more common word.  Thanks though!

**Comment by PrashantMehta-coder** [comment]
Yahh.. You are 100% right.

**Pull request closed without merging**
