### PR TITLE
Docs: README Markdown linting

### PR DESCRIPTION
**Pull request by mchaker**
**Issue number:**

#2282 

**Description of changes:**

Standardize list item characters to `*` and add newlines
between paragraphs. Automatic linting from within VS Code.

**Testing done:**

eyeballs only 👀 

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by jpculp — APPROVED** [review]
Nice. It might be worth iterating through some of the other README's that aren't auto-generated as well. (see `sources/api` and `sources/updater`)

**Review by stmcginnis — APPROVED** [review]
This will be good if we decide to enable some sort of markdown lint checking.

**Review by zmrow — APPROVED** [review]

**Comment by mchaker** [comment]
I did some digging and the linter is markdownlint, using Microsoft Docs Authoring Pack rules in VScode. 

Adding the rules to a pipeline/github action should be possible.

**Comment by mchaker** [comment]
I found what I think are the rules used by the Microsoft Docs Authoring Pack VScode extension (applied via `markdownlint`): https://github.com/microsoft/vscode-docs-authoring/tree/main/packages/docs-linting/markdownlint-custom-rules

**Pull request merged**
