### PR TITLE
[1.14.x] Cherry-pick #3137, #3138, #3139

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
N/A

**Description of changes:**
Cherry-picks  #3137, #3138, #3139

**Testing done:**
See referenced PRs for testing info.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
Host-ctr changes look good!!

**Review by stmcginnis — APPROVED** [review]
Lgtm

**Review by stmcginnis — APPROVED** [review]
Lgtm

**Review by zmrow — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
