### PR TITLE
docker: update to 19.03.15

### LINKED ISSUE #1305: update to Docker 19.03.15
[Docker 19.03.15 is out!](https://github.com/moby/moby/releases/tag/v19.03.15)

### PR DESCRIPTION
**Pull request by webern**
**Issue number:**

Closes #1305

**Description of changes:**

Update docker to 19.03.15

**Testing done:**

Ran an ECS task on x86 and on arm, it worked!

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by tjkirch — APPROVED** [review]
Should we update docker-init's version to match as well?  (It's just intended to match, it doesn't reflect upstream.)

**Comment by webern** [comment]
> Should we update docker-init's version to match as well? (It's just intended to match, it doesn't reflect upstream.)

You mean in docker-init.spec? I don't know what it means. Should we?

**Comment by tjkirch** [comment]
> You mean in docker-init.spec? I don't know what it means. Should we?

We should, yeah.  We don't version that package to match upstream tini (which is 0.19.0), we have it match our Docker packaging, since we sort of "repackage" it as docker-init.

**Comment by webern** [comment]
> > You mean in docker-init.spec? I don't know what it means. Should we?
> 
> We should, yeah. We don't version that package to match upstream tini (which is 0.19.0), we have it match our Docker packaging, since we sort of "repackage" it as docker-init.

I see that version string in `docker-proxy` as well. Should I change it there as well?

**Comment by tjkirch** [comment]
> I see that version string in `docker-proxy` as well. Should I change it there as well?

Ah, good catch, I always forget about proxy.  If you look in the spec file there, we also have to check that the libnetwork commit hasn't changed, but it looks like we're [still good there](https://github.com/moby/moby/blob/v19.03.15/vendor.conf#L41), so yeah, just updating the version number to match Docker.

**Comment by webern** [comment]
> webern force-pushed the webern:docker branch from 4a6abf3 to 57d721f

Bump version in docker-init and docker-proxy

**Review by tjkirch — APPROVED** [review]

**Review by samuelkarp — APPROVED** [review]

**Review by bcressey — APPROVED** [review]

**Pull request merged**
