### PR TITLE
Update default host containers

### PR DESCRIPTION
**Pull request by jpculp**
**Issue number:**

https://github.com/bottlerocket-os/bottlerocket/issues/1595
https://github.com/bottlerocket-os/bottlerocket/issues/1607

**Description of changes:**

This updates the default admin container from v0.7.0 to v0.7.1
and the default control container from v0.5.0. to v0.5.1.

**Testing done:**

Using a custom TUF repo, upgraded and downgraded between 1.1.1 and 1.1.2 and verified both container changes.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by tjkirch — COMMENTED** [review]
LGTM pending testing.

**Review by zmrow — COMMENTED** [review]
Can we also bump the versions of the host containers for VMware variants? :)

**Comment by jpculp** [comment]
Bumped host containers for VMware variants.

**Review by zmrow — APPROVED** [review]
:paintbrush:

**Review by webern — APPROVED** [review]

**Pull request merged**
