### PR TITLE
build: update SDK to v0.42.0

### PR DESCRIPTION
**Pull request by sumukhballal**
**Issue number:**

Closes #

**Description of changes:**

Updates bottlerocket sdk to v0.42.0.

**Testing done:**

- [x] Built aws-ecs-1 variant of Bottlerocket on aarch64.
- [x] Built aws-ecs-1 variant of Bottlerocket on x86_64.
- [ ] Created an AMI.
- [ ] Spun an instance.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by sumukhballal** [comment]
Just a draft PR. This will be tackled next week after a release of v0.42.0 of the SDK.

**Comment by sumukhballal** [comment]
Added a temporary commit after pushing the new Bottlerocket SDK version 0.42.0. This will be updated once tested.

**Comment by sumukhballal** [comment]
Pushed Clippy fixes.

**Review by webern — APPROVED** [review]

**Review by webern — CHANGES_REQUESTED** [review]
Actually I just realized we are code frozen and this probably needs to be wrapped into the fit repo splitting PRs.

**Comment by bcressey** [comment]
The SDK update was done in #4060 instead.

**Pull request closed without merging**
