### PR TITLE
Archive migrations before v1.12.0

### PR DESCRIPTION
**Pull request by mjsterckx**
**Description of changes:**

Archiving migrations improves build speed. Following the example of https://github.com/bottlerocket-os/bottlerocket/pull/2518.

**Testing done:**

Before this change, the contents of the migrations rpm shows:
```
ubuntu@ip-172-31-65-200:~/dev/bottlerocket/build/rpms$ rpm -qlp bottlerocket-x86_64-migrations-0.0-0.x86_64.rpm
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.10.1_container-runtime
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.10.1_container-runtime-metadata
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_aws-admin-container-v0-9-3
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_aws-config-settings
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_aws-control-container-v0-6-4
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_aws-creds
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_aws-creds-metadata
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_credential-providers
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_ecs-additional-configurations
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_kubelet-new-config-files
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_kubelet-tls-config
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_kubelet-tls-files
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_public-admin-container-v0-9-3
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations/migrate_v1.11.0_public-control-container-v0-6-4
```

After this change, the contents of the migrations rpm is now just the directory and nothing else:
```
ubuntu@ip-172-31-65-200:~/dev/bottlerocket/build/rpms$ rpm -qlp bottlerocket-x86_64-migrations-0.0-0.x86_64.rpm
/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/migrations
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
Looks right and matches past archive migrations patches.

**Comment by etungsten** [comment]
We should merge https://github.com/bottlerocket-os/bottlerocket/pull/2605 first, then archive everything before `1.12.0`.

Can you please also do some testing akin to what was done in https://github.com/bottlerocket-os/bottlerocket/pull/2357?

**Review by webern — APPROVED** [review]

**Comment by mjsterckx** [comment]
^ Removed 1.11.0 migrations as well

**Review by etungsten — APPROVED** [review]

**Review by webern — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
Updates look good.

**Pull request merged**
