### PR TITLE
Drop Kubernetes 1.22 variants

### LINKED ISSUE #2844: Remove K8s 1.22 variants by May 2023
Kubernetes 1.22 went out of upstream support in April, 2022. AWS EKS is maintaining support for 1.22 until [May 1st, 2023](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). Bottlerocket will end support of our K8s 1.22 variants at that time.

While you’ll still be able to launch *-k8s-1.22 nodes beyond May 1st, 2023, we’ll no longer provide updated *-k8s-1.22 images, and the Bottlerocket repositories will no longer receive new updates for nodes running K8s 1.22 variants.

We recommend you replace existing Bottlerocket K8s 1.22 nodes with [a newer variant](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#variants) - ideally the latest your Kubernetes cluster supports.

For instructions on how to migrate your aws-k8s-1.22 nodes to newer supported versions, please consult the [EKS documentation for updating clusters](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) or reach out to us through your AWS support channels for additional questions.

### PR DESCRIPTION
**Pull request by stmcginnis**
**Issue number:**

Closes #2844

**Description of changes:**

This removes the 1.22 k8s variants. Kubernetes 1.22 went out of upstream support in April, 2022. AWS EKS is maintaining support for 1.22 until [May 1st, 2023](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). 

**_Note to reviewers_**

See #2700, #2421, and #2316 for examples of past removals of k8s version variants.

**Testing done:**

`cargo make -e BUILDSYS_VARIANT=aws-k8s-1.23 -e BUILDSYS_ARCH=x86_64`

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Converted to draft until it is officially decided when this should happen.

**Review by yeazelm — APPROVED** [review]

**Review by jpmcb — CHANGES_REQUESTED** [review]
A few additional suggestions:

---

Update `BUILDING.md`

https://github.com/bottlerocket-os/bottlerocket/blob/bf7dec94ac64ac153515850ca7f9baea3cfb8d91/BUILDING.md?plain=1#L150-L157

---

There's a few spots in the `README.md` that call out 1.22 as a specific variant version:

https://github.com/bottlerocket-os/bottlerocket/blob/bf7dec94ac64ac153515850ca7f9baea3cfb8d91/README.md?plain=1#L61-L63

**Comment by stmcginnis** [comment]
As far as examples in the docs and code, we've taken the stance on some of them in the past not to update every time since they are only examples. As long as it doesn't apply to a specific instruction to the user, they shouldn't be included as an ongoing maintenance item.

But the list of variants was definitely a miss. Will update that now!

**Comment by jpmcb** [comment]
> As far as examples in the docs and code, we've taken the stance on some of them in the past not to update every time since they are only examples. 

If the variant is gone from the main branch, someone pulls the repository, and follows the instructions in `BUILDING.md`, doing ` cargo make -e BUILDSYS_VARIANT=aws-k8s-1.22` will fail.

We should update the docs to be as up to date as possible with the tip of `develop` - otherwise, it'll fall into disarray.

Edit: for example:

```
[cargo-make] INFO - Running Task: build-variant
ManifestParse: Failed to read manifest file '/home/ubuntu/workspace/bottlerocket-os/bottlerocket/variants/aws-k8s-1.22/Cargo.toml': No such file or directory (os error 2)
error: manifest path `variants/aws-k8s-1.22/Cargo.toml` does not exist
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

**Comment by stmcginnis** [comment]
> > As far as examples in the docs and code, we've taken the stance on some of them in the past not to update every time since they are only examples.
> 
> If the variant is gone from the main branch, someone pulls the repository, and follows the instructions in `BUILDING.md`, doing ` cargo make -e BUILDSYS_VARIANT=aws-k8s-1.22` will fail.
> 
> We should update the docs to be as up to date as possible with the tip of `develop` - otherwise, it'll fall into disarray.

I disagree for example snippets. If they ask to build a 1.22 variant and it doesn't exist, we would want that to fail. But I also don't think we want or expect someone building Bottlerocket to blindly copy and paste commands with no idea what they are asking for.

Let's see what other folks think. Happy to go with the consensus, but that's my 2 cents.

**Review by zmrow — APPROVED** [review]

**Comment by etungsten** [comment]
> I disagree for example snippets. If they ask to build a 1.22 variant and it doesn't exist, we would want that to fail. But I also don't think we want or expect someone building Bottlerocket to blindly copy and paste commands with no idea what they are asking for.

Ideally any code snippet we provide in the examples should not fail. Traditionally we'd update these every time we update the default variant to the latest `aws-k8s-*` variant but it seems like we've missed this one. It's weird that we have a divergence and we should probably fix it.

See https://github.com/bottlerocket-os/bottlerocket/pull/2593/files

**Comment by stmcginnis** [comment]
> Traditionally we'd update these every time we update the default variant

OK, fair enough. I will update it to the current default to increase the chances it will be found the next time that is bumped.

**Review by etungsten — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
