### PR TITLE
Update host containers

### PR DESCRIPTION
**Pull request by vyaghras**
**Description of changes:**
Update the admin and control host containers to bottlerocket-admin-container v0.11.7 and bottlerocket-control-container v0.7.11. Also add migrations move to these versions on upgrade.

**Testing done:**

- [x] `cargo make check-migrations`
- [x] Build Bottlerocket AMI and check the version via API Client
```
apiclient get settings.host-containers
{
  "settings": {
    "host-containers": {
      "admin": {
        "enabled": true,
        "source": "**********.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.11.7",
        "superpowered": true,
        "user-data": "***********"
      },
      "control": {
        "enabled": true,
        "source": "*********.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-control:v0.7.11",
        "superpowered": false
      }
    }
  }
}
```

- [x] Test migration from `v1.19.4` to `v1.19.5`, host container versions are correctly picked up. (Same output as above)
```
apiclient get os
{
  "os": {
    "arch": "x86_64",
    "build_id": "d2ac549f-dirty",
    "pretty_name": "Bottlerocket OS 1.19.5 (aws-k8s-1.29)",
    "variant_id": "aws-k8s-1.29",
    "version_id": "1.19.5"
  }
}
```
```
apiclient get settings.host-containers
{
  "settings": {
    "host-containers": {
      "admin": {
        "enabled": true,
        "source": "******.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.11.7",
        "superpowered": true,
        "user-data": "******"
      },
      "control": {
        "enabled": true,
        "source": "******.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-control:v0.7.11",
        "superpowered": false
      }
    }
  }
}
```
- [x] Test rollback to `v1.19.5` from `v1.19.4`.
```
apiclient get os
{
  "os": {
    "arch": "x86_64",
    "build_id": "4f0a078e",
    "pretty_name": "Bottlerocket OS 1.19.4 (aws-k8s-1.29)",
    "variant_id": "aws-k8s-1.29",
    "version_id": "1.19.4"
  }
}
```
```
apiclient get settings.host-containers
{
  "settings": {
    "host-containers": {
      "admin": {
        "enabled": true,
        "source": "****.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.11.6",
        "superpowered": true,
        "user-data": "*****"
      },
      "control": {
        "enabled": true,
        "source": "****.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-control:v0.7.10",
        "superpowered": false
      }
    }
  }
}
```
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by monirul — COMMENTED** [review]
We should not expose the user data in the PR description. This can leak sensitive data. For example, your user data actually contains ssh key details.
`{"ssh":{"authorized-keys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQA... vyaghras-us-west-2"]}}%`

technically speaking your key is compromised. It would be better if you revoke the key.

**Comment by yeazelm** [comment]
@monirul `"ssh-rsa AAAAB3NzaC1yc2EAAAADAQA... vyaghras-us-west-2` is a public key. It is not compromised but nonetheless this is a good idea to avoid publishing specifics from user data in these reivews.

**Comment by vyaghras** [comment]
⬆️ Fix the build error for `Cargo fmt`

**Review by yeazelm — APPROVED** [review]
LGTM!

**Review by sam-berning — APPROVED** [review]

**Pull request merged**
