### PR TITLE
Update Kubernetes version for 1.24, 1.23 and update release number for other versions

### PR DESCRIPTION
**Pull request by zafs23**
**Issue number:**

Closes #

**Description of changes:**

**Testing done:**

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Is it a concern that package SHAs have changed for the same release, just hosted somewhere new?

**Comment by stmcginnis** [comment]
> Is it a concern that package SHAs have changed for the same release, just hosted somewhere new?

Yeah, something isn't right with these new links:

```txt
  Failed to verify file 'kubernetes-src.tar.gz' with hash 'b235054986be7bbb46893b2e781398a4346e9e7a5da96e19bcec93b4d92b034db5de5bd3265220e045a912b4bdb2af1fcf6cf170933c6d9e0c74223153e4658e'
  Failed to fetch 'https://cache.bottlerocket.aws/kubernetes-src.tar.gz/b235054986be7bbb46893b2e781398a4346e9e7a5da96e19bcec93b4d92b034db5de5bd3265220e045a912b4bdb2af1fcf6cf170933c6d9e0c74223153e4658e/kubernetes-src.tar.gz': 403 Forbidden
```

**Comment by zafs23** [comment]
> Is it a concern that package SHAs have changed for the same release, just hosted somewhere new?

@stmcginnis I have revert the changes in 1.21 and all tests passed.

**Comment by stmcginnis** [comment]
Thanks @zafs23! I've uploaded the packages to our look aside cache, so the tests can get to things now.

Would you mind squashing your commits into one?

**Review by stmcginnis — APPROVED** [review]
As a sanity check:

```bash
cargo make
cargo make ami
# edit eksctl yaml file to include AMI ID
eksctl create cluster -f eksctl.yaml
kubectl get all -A
kubectl apply -f test-pod.yaml
kubectl get pod
```

Everything looks good with the 1.22 release.

**Comment by zafs23** [comment]
> Thanks @zafs23! I've uploaded the packages to our look aside cache, so the tests can get to things now.
> 
> Would you mind squashing your commits into one?

@stmcginnis Done!

**Review by stmcginnis — APPROVED** [review]
Thanks!

**Comment by stmcginnis** [comment]
Performed same sanity check as above for the 1.23 release. k8s cluster was operational and able to deploy pods.

**Review by etungsten — APPROVED** [review]
Built and testing aws-k8s-1.24 based on these changes. Nodes come up fine in the cluster and can run basic workloads.
```
$ kubectl get nodes -o wide
NAME                                          STATUS   ROLES    AGE     VERSION               INTERNAL-IP     EXTERNAL-IP      OS-IMAGE                                KERNEL-VERSION   CONTAINER-RUNTIME
ip-192-168-2-111.us-west-2.compute.internal   Ready    <none>   3m27s   v1.24.8-eks-8850f1d   192.168.2.111   54.202.209.134   Bottlerocket OS 1.12.0 (aws-k8s-1.24)   5.15.59          containerd://1.6.12+bottlerocket
ip-192-168-7-43.us-west-2.compute.internal    Ready    <none>   3m11s   v1.24.8-eks-8850f1d   192.168.7.43    54.149.159.203   Bottlerocket OS 1.12.0 (aws-k8s-1.24)   5.15.59          containerd://1.6.12+bottlerocket

```

**Pull request merged**
