### PR TITLE
Update bootstrap-containers/README.md

### PR DESCRIPTION
**Pull request by effy-coding**
`VAR_DIR` (undeclared) => `HOST_VAR_DIR`

**Issue number:**

**Description of changes:**

**Testing done:**

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by zmrow — APPROVED** [review]
LGTM!  Thanks!!

:fondue:

**Review by etungsten — CHANGES_REQUESTED** [review]
The `README.md` is generated from the crate's doc comments at the top of `main.rs` here:
https://github.com/bottlerocket-os/bottlerocket/blob/6e5850cdfce11cc6c9c5420e50077aba90e27e28/sources/api/bootstrap-containers/src/main.rs#L42-L44

The fix should go there as well. If you have cargo installed, you can regenerate the README by running `cargo check` to invoke the `build.rs` script.

**Comment by arnaldo2792** [comment]
Thanks! LGTM provided the change suggested by @etungsten is addressed :+1:

**Comment by effy-coding** [comment]
@etungsten I changed comment of bottlerocket/sources/api/bootstrap-containers/src/main.rs Not README.md

Thanks

@arnaldo2792 @zmrow

**Comment by etungsten** [comment]
> I changed comment of bottlerocket/sources/api/bootstrap-containers/src/main.rs Not README.md

Hi @dangen-effy , the change would need to happen for both `bottlerocket/sources/api/bootstrap-containers/src/main.rs` and `bottlerocket/sources/api/bootstrap-containers/README.md`. Sorry for being unclear.

**Comment by effy-coding** [comment]
@etungsten It was my mistake! Now i edited both.

**Review by etungsten — APPROVED** [review]

**Review by zmrow — APPROVED** [review]
:+1:

**Review by arnaldo2792 — APPROVED** [review]

**Pull request merged**
