### PR TITLE
docs: Update Bottlerocket version in provisioning

### PR DESCRIPTION
**Pull request by raykrueger**
PROVISIONING-METAL doc refernces 1.9 which is well aged. This commit simply updates us to 1.12 for easy copy and paste.

**Issue number:**
None

**Description of changes:**
Simply updating the version in the docs.

**Testing done:**
Tested via hands-on metal provisioning

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by yeazelm — APPROVED** [review]
We have other versions like the SDK that should be updated in this file, but this is a good catch!

**Review by zmrow — APPROVED** [review]
Thanks!

:tada:

**Comment by raykrueger** [comment]
Is this ready to merge now? ;)

**Comment by yeazelm** [comment]
Just merged it! Thanks for the PR!

**Pull request merged**
