### PR TITLE
prairiedog: treat value-less key differently than "empty" values

### LINKED ISSUE #2359: Prairiedog and the kernel may disagree about parsing boot config keys without values
**Image I'm using:** Build of metal-dev variant fresh off develop

**What I expected to happen:**

When using the example user data from the boot settings section of the `README.md`, ...

```
[settings.boot.kernel-parameters]
"console" = [
  "tty0",
  "ttyS1,115200n8",
]
"crashkernel" = [
  "2G-:256M",
]
"slub_debug" = [
  "options,slabs",
]
"usbcore.quirks" = [
  "0781:5580:bk",
  "0a5c:5834:gij",
]

[settings.boot.init-parameters]
"log_level" = ["debug"]
"splash" = []
```

...I expected those settings to always reflect what the kernel and systemd would see on boot.

**What actually happened:**

Prairiedog may generate the following boot config...:

```
bash-5.1# cat /var/lib/bottlerocket/bootconfig.data 
kernel.slub_debug = "options,slabs"
kernel.crashkernel = "2G-:256M"
kernel.usbcore.quirks = "0781:5580:bk", "0a5c:5834:gij"
kernel.console = "tty0", "ttyS1,115200n8"
init.splash = 
init.log_level = "debug"
```

...which on next boot is read by the kernel as:

```
bash-5.1# cat /proc/bootconfig 
kernel.slub_debug = "options,slabs"
kernel.crashkernel = "2G-:256M"
kernel.usbcore.quirks = "0781:5580:bk", "0a5c:5834:gij"
kernel.console = "tty0", "ttyS1,115200n8"
init.splash = 'init.log_level = "debug"'
```

Note that the `log_level` key got pulled in as the value for the actually value-less `splash` key.

**How to reproduce the problem:**

Put the boot settings fragment from above into your user data. There seems to be a random component to it, and it may take a few (clean) boots to hit.

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**

Resolves https://github.com/bottlerocket-os/bottlerocket/issues/2359

**Description of changes:**
```
    prairiedog: treat value-less key differently than "empty" values
    
    Before this change, prairedog did no special handling for value-less
    bootconfig keys and would just write out 'key ='. The kernel is
    insensitive to whitespace so it would grab the next k/v from the
    bootconfig and substitute it for the value.
    
    With this change, prairiedog now differentiates between value-less keys
    and keys with empty values (e.g. 'key = ""') both in parsing an existing
    bootconfig file as well as when it generates the bootconfig initrd from
    existing settings.
    
    When the key is value-less, prariedog will just write out the key
    without '=' for its line entry in the bootconfig (e.g. just 'key').

```

**Testing done:**
The new unit test passes.
Built aws-k8s-1.23 and passed the following user-data:
```
[settings.boot.kernel-parameters]
"console" = [
    "tty0",
    "ttyS1,115200n8",
]
"crashkernel" = [
    "2G-:256M",
]
"slub_debug" = [
    "options,slabs",
]
"usbcore.quirks" = [
    "0781:5580:bk",
    "0a5c:5834:gij",
]
[settings.boot.init-parameters]
"log_level" = ["debug"]
"splash" = []
```
Host comes up fine. Prairiedog writes out the bootconfig as expected. Note how `init.splash` is value-less:
```bash
bash-5.1# cat /var/lib/bottlerocket/bootconfig.data                                                      
kernel.crashkernel = "2G-:256M"                                                                          
kernel.slub_debug = "options,slabs"                                                                      
kernel.usbcore.quirks = "0781:5580:bk", "0a5c:5834:gij"                                                  
kernel.console = "tty0", "ttyS1,115200n8"                                                                
init.log_level = "debug"                                                                                 
init.splash          
```

After a reboot, kernel interprets the bootconfig correctly:
```
bash-5.1# cat /proc/bootconfig 
kernel.console = "tty0", "ttyS1,115200n8"
kernel.crashkernel = "2G-:256M"
kernel.slub_debug = "options,slabs"
kernel.usbcore.quirks = "0781:5580:bk", "0a5c:5834:gij"
init.splash = ""
init.log_level = "debug"
```

The kernel commandline is written out as expected:
```bash
bash-5.1# cat /proc/cmdline 
crashkernel="2G-:256M" slub_debug="options,slabs" usbcore.quirks="0781:5580:bk" usbcore.quirks="0a5c:5834:gij" console="tty0" console="ttyS1,115200n8" BOOT_IMAGE=(hd0,gpt3)/vmlinuz console=tty0 console=ttyS0,115200n8 net.ifnames=0 netdog.default-interface=eth0:dhcp4,dhcp6? quiet bootconfig root=/dev/dm-0 rootwait ro raid=noautodetect random.trust_cpu=on selinux=1 enforcing=1 dm_verity.max_bios=-1 dm_verity.dev_wait=1 "dm-mod.create=root,,,ro,0 1884160 verity 1 PARTUUID=e00ffc4b-0ffd-4c54-96da-179dcf308bb0/PARTNROFF=1 PARTUUID=e00ffc4b-0ffd-4c54-96da-179dcf308bb0/PARTNROFF=2        4096 4096 235520 1 sha256 5370126d558ff5a2c1b100c3efb1da864dc293e4f314216647743fd96c50e70b 227c3407308c594bb0790cdfa7b322d04ec509ceaa32ace7198c23e285a5817f        2 restart_on_corruption ignore_zero_blocks" -- systemd.log_target=journal-or-kmsg systemd.log_color=0 systemd.show_status=true log_level="debug" splash
```

Note how on the kernel command line, `splash` is just written out as `splash` for the init param.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by mchaker — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
Great having test coverage!

**Review by webern — APPROVED** [review]

**Review by zmrow — APPROVED** [review]
:mechanic: 

Nice work!

**Review by arnaldo2792 — APPROVED** [review]

**Comment by bcressey** [comment]
According to the boot config docs:
> There can be a key which doesn’t have value or has an empty value. Those keys are used for checking if the key exists or not (like a boolean).

I would expect to have a way to render just `splash` onto the kernel command line, rather than `splash=""`. Is there a syntax in the boot config format like one of these that would work?
```
splash =
splash
```

**Comment by etungsten** [comment]
`splash =` is what prompted the linked issue. The kernel apparently is insensitive to whitespace/newlines when parsing the `bootconfig` from `initrd` so it grabs the next line as the value for `splash`. I'm trying out just `splash` to see if it likes it better.

**Comment by etungsten** [comment]
Push above changes approach to value-less keys. Prairiedog now differentiates between value-less keys and keys with empty values. Value-less keys are always written out to the bootconfig with just their key.

Updated PR description to include new testing details. I verified the kernel no longer misinterprets value-less keys like `splash` and treats it as its own bootconfig entry.

**Review by webern — APPROVED** [review]

**Comment by etungsten** [comment]
Push above adds to the unit test to show that `key =` is still parse-able by prairiedog

**Review by bcressey — APPROVED** [review]

**Review by mchaker — APPROVED** [review]
Thank you so much for this!

**Pull request merged**
