### PR TITLE
Bump cargo-make to 0.30.0

### PR DESCRIPTION
**Pull request by gliptak**
**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by zmrow — APPROVED** [review]
💎 

Thanks for the contribution!

This looks pretty safe to me, especially since the build is fine.

Paging @bcressey / @iliana

**Review by bcressey — APPROVED** [review]
🔆

**Review by jahkeup — APPROVED** [review]
:+1: :hammer: :shipit:

**Comment by iliana** [comment]
Thanks!

**Pull request merged**
