### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
**Issue number:**

**Description of changes:**

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/bottlerocket/commit/5b60d83ae286ea079c5b86d6beaea6caa3ae2f59#commitcomment-62185921

**Testing done:**

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/bottlerocket/commit/7fc974bb348d1fcbc7333dce9699957fa10aa294

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by zmrow — APPROVED** [review]
Thanks for this!  LGTM.

I'd like another set of eyes on it, and the actions to run, but these changes shouldn't break anything.

**Review by webern — APPROVED** [review]

**Comment by cbgbt** [comment]
Thanks for submitting this change! Would you be willing to squash this into a single commit? That may make it easier to navigate the commit history.

**Comment by jsoref** [comment]
Sure, more than happy. I try to delay until after approval because often there's pushback on individual changes.

I'll try to do that tonight. If there's a specific style, let me know, otherwise it'll probably be:

```
Spelling

* term
* word
* ...
```

**Comment by cbgbt** [comment]
Oh gosh, I didn't see this reply. I was told that github had a squash feature in PRs and decided we could do that from our end. Sorry about that! Thanks again for submitting this fix!

**Comment by jsoref** [comment]
I'm quite happy to not do it. You saved me some work. So that's totally fine w/ me. Thanks!

**Pull request merged**
