### PR TITLE
[1.14.x] Updated to EKS-D 1.22-27

### LINKED ISSUE #3107: Update to EKS-D 1.22-27
**What I'd like:**
Latest version of EKS-D 1.22.

---

#### This will be one of our last releases of 1.22! We will not be updating this version after June 4, 2023. You will still have access to the tarballs indefinitely.

---

**Any alternatives you've considered:**

### PR DESCRIPTION
**Pull request by kschumy**
**Issue number:**

Closes #3107

**Description of changes:**

Latest version of EKS-D 1.22.

**⚠️⚠️⚠️ IMPORTANT ⚠️⚠️⚠️**
**This will be one of our last releases of 1.22! We will not be updating this version after June 4, 2023. You will still have access to the tarballs indefinitely.**

**Testing done:**

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Waiting to see if we need this in Bottlerocket. I believe the 1.14.0 release was the last release planned for 1.22 for Bottlerocket, so we might not want to take this update.

**Comment by stmcginnis** [comment]
Think we're going to backport this for a potential 1.14 point release.

**Review by stmcginnis — APPROVED** [review]
Built, deployed, and ran `sonobuoy run --mode=quick`. Everything passed.

**Review by etungsten — APPROVED** [review]

**Comment by bcressey** [comment]
There's a weird merge commit showing up - can we cherry-pick the commit from develop instead?

**Comment by stmcginnis** [comment]
I updated this PR to go directly to `1.14.x` since we were dropping 1.22 on `develop`. I didn't notice if that was included prior to doing that or not. It probably would have been better to follow normal procedure and merge to `develop` first, then just cherry pick the one commit back. But since 1.22 is now dropped, that probably would not be worth the effort.

I can update this PR to get rid of that merge commit.

**Review by bcressey — APPROVED** [review]

**Pull request merged**
