### PR TITLE
Remove aws-k8s-1.19 variant

### LINKED ISSUE #2228: Deprecate aws-k8s-1.19 variant by August 2022
Kubernetes 1.19 went out of upstream support in August, 2021. AWS EKS is maintaining support for 1.19 until [August 1st, 2022](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). Bottlerocket will deprecate support of our `aws-k8s-1.19` variant at that time.

While you’ll still be able to launch `aws-k8s-1.19` nodes beyond August 1st, 2022, we’ll no longer provide updated `aws-k8s-1.19` images, and the Bottlerocket repositories will no longer receive new updates for nodes running `aws-k8s-1.19`.

We recommend you replace existing Bottlerocket `aws-k8s-1.19` nodes with [a newer variant](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#variants) such as `aws-k8s-1.22` - ideally the latest your Kubernetes cluster supports.

For instructions on how to migrate your nodes to newer supported versions, please consult the [EKS documentation for updating clusters](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) or reach out to us through your AWS support channels for additional questions.

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
Resolves https://github.com/bottlerocket-os/bottlerocket/issues/2228

**Description of changes:**
```
    Remove aws-k8s-1.19 variant
    
    EKS ended 1.19 support on August 1st, 2022.
```
```
    SECURITY_GUIDANCE: remove reference to aws-k8s-1.19
```
```
    README: clarify defaults for settings.kernel.lockdown
    
    Clarifies where lockdown is set to "none" by default
```
```
    packages: remove kernel-5.4 package
    
    There are no longer any variants that still depend on the 5.4 kernel.
```
```
    packages: remove kubernetes-1.19 package
```
Like https://github.com/bottlerocket-os/bottlerocket/pull/2044 removing the 1.18 variant, this removes the `aws-k8s-1.19` variant and any packages only used by the 1.19 variant. It's no longer supported by K8s upstream or EKS. Deprecation was communicated in the issue linked above that has been pinned in our issue list.

**Testing done:**
Confirmed unit tests pass, 1.19 is no longer referenced and doesn't build, and 1.20 is still healthy.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by bcressey — APPROVED** [review]
🎉

**Review by stmcginnis — APPROVED** [review]
Looks like everything is covered.

**Review by zmrow — APPROVED** [review]
:cake:

**Comment by bcressey** [comment]
@etungsten - this looks ready to merge but I'd like to merge #2323 first so it's easier to cherry-pick for a point release.

**Review by markusboehme — APPROVED** [review]

**Comment by markusboehme** [comment]
I merged #2323, so this one should be good to go now. :ship:

**Comment by etungsten** [comment]
Push above rebases onto develop and resolves conflicts

**Pull request merged**
