### PR TITLE
Prepare for v1.5.0 Release

### PR DESCRIPTION
**Pull request by cbgbt**
* [x] This must be rebased upon #1872 before being merged.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by samuelkarp — APPROVED** [review]
Looks good pending the changes from the other PR.

**Comment by bcressey** [comment]
LGTM ☃️

**Review by webern — APPROVED** [review]

**Review by jpculp — APPROVED** [review]

**Comment by cbgbt** [comment]
The above change just rebases this atop develop.

**Review by arnaldo2792 — APPROVED** [review]
:pickup_truck:

**Review by bcressey — APPROVED** [review]

**Pull request merged**
