### PR TITLE
Drop AWS K8s 1.23 variants

### LINKED ISSUE #4083: Remove aws-k8s-1.23 variants by October 2024
Amazon EKS will end extended support of Kubernetes 1.23 on [October 11, 2024](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). Support for the `aws-k8s-1.23*` variants of Bottlerocket will end on the same date.

While you still can launch aws-k8s-1.23 nodes, we will not provide updated aws-k8s-1.23 images after October 11, 2024,  and the Bottlerocket repositories will no longer receive new updates for nodes running k8s 1.23 variants. We recommend you replace existing Bottlerocket k8s 1.23 nodes with [a newer variant](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#variants) - ideally the latest your Kubernetes cluster supports.

For instructions on how to migrate your aws-k8s-1.23 nodes to newer supported versions, please consult the [EKS documentation for updating clusters](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) or reach out to us through your AWS support channels (https://aws.amazon.com/support/) for additional questions.

### PR DESCRIPTION
**Pull request by ginglis13**
**Issue number:**

Closes #4083

**Description of changes:**

Drop the `aws-k8s-1.23` and `aws-k8s-1.23-nvidia` variants following the EKS support policy. The variants go EOL in EKS on October 11.

**Testing done:**

`cargo make` succeeds, `cargo make -e BUILDSYS_VARIANT=aws-k8s-1.23` and `cargo make -e BUILDSYS_VARIANT=aws-k8s-1.23-nvidia` fail.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by larvacea — APPROVED** [review]

**Review by larvacea — APPROVED** [review]

**Comment by koooosh** [comment]
Do we also need to remove [the k8s-1.23 pkg from the core-kit](https://github.com/bottlerocket-os/bottlerocket-core-kit/tree/develop/packages/kubernetes-1.23)?

**Comment by ginglis13** [comment]
> Do we also need to remove [the k8s-1.23 pkg from the core-kit](https://github.com/bottlerocket-os/bottlerocket-core-kit/tree/develop/packages/kubernetes-1.23)?

Yes that work is on my plate, but it's not a requirement for this PR

**Review by bcressey — APPROVED** [review]

**Comment by koooosh** [comment]
Also, I see a few more hits for `k8-1.23` in this repo ([search link](https://github.com/search?q=repo%3Abottlerocket-os%2Fbottlerocket%20k8s-1.23&type=code)), particularly:
- [settings-defaults](https://github.com/bottlerocket-os/bottlerocket/blob/acfd0abee25b6061fcff30206856d36271a12d73/packages/settings-defaults/settings-defaults.spec#L72)
- [settings-plugins](https://github.com/bottlerocket-os/bottlerocket/blob/acfd0abee25b6061fcff30206856d36271a12d73/packages/settings-plugins/settings-plugins.spec#L59)

Should these be removed too?

**Comment by ginglis13** [comment]
> Also, I see a few more hits for k8-1.23 in this repo ([search link](https://github.com/search?q=repo%3Abottlerocket-os%2Fbottlerocket%20k8s-1.23&type=code)), particularly:

    [settings-defaults](https://github.com/bottlerocket-os/bottlerocket/blob/acfd0abee25b6061fcff30206856d36271a12d73/packages/settings-defaults/settings-defaults.spec#L72)
    [settings-plugins](https://github.com/bottlerocket-os/bottlerocket/blob/acfd0abee25b6061fcff30206856d36271a12d73/packages/settings-plugins/settings-plugins.spec#L59)

> Should these be removed too?

Those were only used by the k8s-1.23 variants, but good callout, I'll follow up removing those

**Pull request merged**
