### PR TITLE
Archive `v1.12.0` migrations in preparation for `v1.13.0` migrations

### PR DESCRIPTION
**Pull request by jpmcb**
**Issue number:**

Closes - N/a

Similar to https://github.com/bottlerocket-os/bottlerocket/pull/2606 and https://github.com/bottlerocket-os/bottlerocket/pull/2518

**Description of changes:**

Archives v1.12.0 migrations in preperation for v1.13.0 migrations (like https://github.com/bottlerocket-os/bottlerocket/pull/2786)

**Testing done:**

Successfully built locally

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by jpmcb** [comment]
Marking as draft - we might want to keep some of the `n-1`, `n-2`, etc. migrations around in case we need to make a "pivot" migration repo that skips versions. Will need to open this up for more discussion before this merges.

**Review by webern — CHANGES_REQUESTED** [review]
I think we should keep migrations around through a few versions in case we need to build development repos that skip versions. During a development workflow recently I wanted to do upgrade downgrade between v1.10.1 and v1.12.0 and needed to build the intervening v1.11.0 tag because migrations had been quickly archived. If the migrations stuck around a little longer, the intervening build would not have been necessary.

**Comment by etungsten** [comment]
> I think we should keep migrations around through a few versions in case we need to build development repos that skip versions. During a development workflow recently I wanted to do upgrade downgrade between v1.10.1 and v1.12.0 and needed to build the intervening v1.11.0 tag because migrations had been quickly archived. If the migrations stuck around a little longer, the intervening build would not have been necessary.

I think in those cases, we can do it in a development branch that reverts this change. Archiving migrations does provide a pretty nice build time improvement and also keeps the number of builds artifacts that we need to sync to TUF repositories down.

**Comment by jpmcb** [comment]
> I think we should keep migrations around through a few versions in case we need to build development repos that skip versions. 

👍🏼 

Closing.

**Pull request closed without merging**
